name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Clone pimoroni-pico
      run: |
        git clone https://github.com/pimoroni/pimoroni-pico.git --depth 1
        cd pimoroni-pico
        git submodule update --init --recursive

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential

    - name: Install Pico SDK
      run: |
        git clone https://github.com/raspberrypi/pico-sdk.git --branch 2.1.0 --depth 1
        cd pico-sdk
        git submodule update --init --recursive

    - name: Build
      run: |
        export PICO_SDK_PATH=${{ github.workspace }}/pico-sdk
        cmake -DPICO_BOARD=pico2_w -B build -S .
        cd build
        make -j$(nproc)

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: uf2loader-pico2w
        path: |
          build/**/*.uf2
          build/**/*.bin
        retention-days: 30
